import typing

from faker import Faker

from apps.contacts import models


def generate_contacts(amount: int = 10, is_mark_as_autogenerated: bool = False) -> typing.Iterator[models.Contact]:
    fake = Faker()

    for _ in range(amount):
        contact_profile = fake.profile()
        yield models.Contact(
            username=contact_profile["username"],
            name=contact_profile["name"],
            birthdate=contact_profile["birthdate"],
            sex=contact_profile["sex"],
            ssn=contact_profile["ssn"],
            company=contact_profile["company"],
            job=contact_profile["job"],
            mail=contact_profile["mail"],
            telephone=fake.phone_number(),
            address=contact_profile["address"],
            is_auto_generated=is_mark_as_autogenerated,
        )
